name: create vsix package

on:
  push:
    # Trigger workflow for commits only, not for tags.
    branches:
      - '**'
  pull_request:
  workflow_dispatch:


jobs:
  create_vsix:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install extension packaging tool (TFX)
      run: npm install -g tfx-cli

    - name: Install package dependencies
      run: npm ci

    - name: Create release vsix package
      run: npm run build

    - name: Upload vsix package
      uses: actions/upload-artifact@v4
      with:
        name: release_vsix_zip
        path: ./*.vsix
        if-no-files-found: error
